name: CI

on:
  - push

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Generate
        run: oapi-codegen --package=main -generate=types,client -o ./render.go ./openapi.yaml
